#ddev-generated
services:
  opensearch:
    container_name: ddev-${DDEV_SITENAME}-opensearch
    hostname: ${DDEV_SITENAME}-opensearch
    image: opensearchproject/opensearch:2.9.0
    expose:
      - "9200"
      - "9600"
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200:9200
      - HTTPS_EXPOSE=9201:9200
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - opensearch:/usr/share/opensearch/data
      - ".:/mnt/ddev_config"

volumes:
  opensearch:
